// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGallop_Resort.Api.Data;

#nullable disable

namespace TheGallop_Resort.Api.Migrations
{
    [DbContext(typeof(GaloppDbContext))]
    [Migration("20260601075538_seedFix")]
    partial class seedFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            Status = 0,
                            TotalPrice = 3598m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            Status = 2,
                            TotalPrice = 3699m
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "erik.johansson@email.com",
                            FirstName = "Erik",
                            LastName = "Johansson",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna.svensson@email.com",
                            FirstName = "Anna",
                            LastName = "Svensson",
                            PhoneNumber = "0709876543"
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomCategoryId");

                    b.HasIndex("RoomNr")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomCategoryId = 1,
                            RoomNr = 1001
                        },
                        new
                        {
                            Id = 2,
                            RoomCategoryId = 1,
                            RoomNr = 1002
                        },
                        new
                        {
                            Id = 3,
                            RoomCategoryId = 2,
                            RoomNr = 1101
                        },
                        new
                        {
                            Id = 4,
                            RoomCategoryId = 2,
                            RoomNr = 1102
                        },
                        new
                        {
                            Id = 5,
                            RoomCategoryId = 3,
                            RoomNr = 1201
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CategoryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomDetailId");

                    b.ToTable("RoomCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryPrice = 999m,
                            RoomDetailId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryPrice = 1799m,
                            RoomDetailId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryPrice = 3499m,
                            RoomDetailId = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Beds")
                        .HasColumnType("int");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("int");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beds = 1,
                            MaxAdults = 1,
                            MaxChildren = 0
                        },
                        new
                        {
                            Id = 2,
                            Beds = 2,
                            MaxAdults = 2,
                            MaxChildren = 2
                        },
                        new
                        {
                            Id = 3,
                            Beds = 3,
                            MaxAdults = 4,
                            MaxChildren = 2
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomReservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adults = 2,
                            BookingId = 1,
                            CheckIn = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 1,
                            PricePerNight = 1789m,
                            RoomId = 3,
                            RoomStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            Adults = 2,
                            BookingId = 2,
                            CheckIn = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            PricePerNight = 3499m,
                            RoomId = 5,
                            RoomStatus = 2
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Booking", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Room", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.RoomCategory", "RoomCategory")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomCategory");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomCategory", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.RoomDetail", "RoomDetail")
                        .WithMany()
                        .HasForeignKey("RoomDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomDetail");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomReservation", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.Booking", "Booking")
                        .WithMany("RoomReservations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGallop_Resort.Models.Models.Room", "Room")
                        .WithMany("RoomReservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Booking", b =>
                {
                    b.Navigation("RoomReservations");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Room", b =>
                {
                    b.Navigation("RoomReservations");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomCategory", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
