// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGallop_Resort.Api.Data;

#nullable disable

namespace TheGallop_Resort.Api.Migrations
{
    [DbContext(typeof(GaloppDbContext))]
    [Migration("20260601084321_MoreSeed")]
    partial class MoreSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            Status = 0,
                            TotalPrice = 3598m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            Status = 0,
                            TotalPrice = 6998m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            Status = 2,
                            TotalPrice = 1799m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 4,
                            Status = 1,
                            TotalPrice = 3499m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 5,
                            Status = 0,
                            TotalPrice = 999m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 6,
                            Status = 0,
                            TotalPrice = 5397m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 7,
                            Status = 2,
                            TotalPrice = 1799m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 8,
                            Status = 0,
                            TotalPrice = 3499m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 9,
                            Status = 0,
                            TotalPrice = 6998m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 10,
                            Status = 2,
                            TotalPrice = 999m
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "erik.johansson@email.com",
                            FirstName = "Erik",
                            LastName = "Johansson",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna.svensson@email.com",
                            FirstName = "Anna",
                            LastName = "Svensson",
                            PhoneNumber = "0709876543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "johan.karlsson@email.com",
                            FirstName = "Johan",
                            LastName = "Karlsson",
                            PhoneNumber = "0701112233"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emma.nilsson@email.com",
                            FirstName = "Emma",
                            LastName = "Nilsson",
                            PhoneNumber = "0702223344"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lucas.andersson@email.com",
                            FirstName = "Lucas",
                            LastName = "Andersson",
                            PhoneNumber = "0703334455"
                        },
                        new
                        {
                            Id = 6,
                            Email = "maja.lindberg@email.com",
                            FirstName = "Maja",
                            LastName = "Lindberg",
                            PhoneNumber = "0704445566"
                        },
                        new
                        {
                            Id = 7,
                            Email = "oscar.berg@email.com",
                            FirstName = "Oscar",
                            LastName = "Berg",
                            PhoneNumber = "0705556677"
                        },
                        new
                        {
                            Id = 8,
                            Email = "sofia.holm@email.com",
                            FirstName = "Sofia",
                            LastName = "Holm",
                            PhoneNumber = "0706667788"
                        },
                        new
                        {
                            Id = 9,
                            Email = "william.ekstrom@email.com",
                            FirstName = "William",
                            LastName = "Ekström",
                            PhoneNumber = "0707778899"
                        },
                        new
                        {
                            Id = 10,
                            Email = "ella.fors@email.com",
                            FirstName = "Ella",
                            LastName = "Fors",
                            PhoneNumber = "0708889900"
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomCategoryId");

                    b.HasIndex("RoomNr")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomCategoryId = 1,
                            RoomNr = 1001
                        },
                        new
                        {
                            Id = 2,
                            RoomCategoryId = 1,
                            RoomNr = 1002
                        },
                        new
                        {
                            Id = 3,
                            RoomCategoryId = 2,
                            RoomNr = 1101
                        },
                        new
                        {
                            Id = 4,
                            RoomCategoryId = 2,
                            RoomNr = 1102
                        },
                        new
                        {
                            Id = 5,
                            RoomCategoryId = 3,
                            RoomNr = 1201
                        },
                        new
                        {
                            Id = 6,
                            RoomCategoryId = 3,
                            RoomNr = 1202
                        },
                        new
                        {
                            Id = 7,
                            RoomCategoryId = 4,
                            RoomNr = 1301
                        },
                        new
                        {
                            Id = 8,
                            RoomCategoryId = 4,
                            RoomNr = 1302
                        },
                        new
                        {
                            Id = 9,
                            RoomCategoryId = 5,
                            RoomNr = 1401
                        },
                        new
                        {
                            Id = 10,
                            RoomCategoryId = 5,
                            RoomNr = 1402
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CategoryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomDetailId");

                    b.ToTable("RoomCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryPrice = 999m,
                            RoomDetailId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryPrice = 1799m,
                            RoomDetailId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryPrice = 3499m,
                            RoomDetailId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryPrice = 1299m,
                            RoomDetailId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryPrice = 2199m,
                            RoomDetailId = 5,
                            Type = 1
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Beds")
                        .HasColumnType("int");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("int");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beds = 1,
                            MaxAdults = 1,
                            MaxChildren = 0
                        },
                        new
                        {
                            Id = 2,
                            Beds = 2,
                            MaxAdults = 2,
                            MaxChildren = 2
                        },
                        new
                        {
                            Id = 3,
                            Beds = 3,
                            MaxAdults = 4,
                            MaxChildren = 2
                        },
                        new
                        {
                            Id = 4,
                            Beds = 1,
                            MaxAdults = 2,
                            MaxChildren = 1
                        },
                        new
                        {
                            Id = 5,
                            Beds = 2,
                            MaxAdults = 3,
                            MaxChildren = 2
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomReservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adults = 2,
                            BookingId = 1,
                            CheckIn = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 1,
                            PricePerNight = 1799m,
                            RoomId = 3,
                            RoomStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            Adults = 2,
                            BookingId = 2,
                            CheckIn = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            PricePerNight = 3499m,
                            RoomId = 5,
                            RoomStatus = 0
                        },
                        new
                        {
                            Id = 3,
                            Adults = 1,
                            BookingId = 3,
                            CheckIn = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            PricePerNight = 999m,
                            RoomId = 1,
                            RoomStatus = 1
                        },
                        new
                        {
                            Id = 4,
                            Adults = 2,
                            BookingId = 4,
                            CheckIn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 2,
                            PricePerNight = 3499m,
                            RoomId = 5,
                            RoomStatus = 1
                        },
                        new
                        {
                            Id = 5,
                            Adults = 1,
                            BookingId = 5,
                            CheckIn = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            PricePerNight = 999m,
                            RoomId = 2,
                            RoomStatus = 0
                        },
                        new
                        {
                            Id = 6,
                            Adults = 2,
                            BookingId = 6,
                            CheckIn = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 1,
                            PricePerNight = 1799m,
                            RoomId = 4,
                            RoomStatus = 0
                        },
                        new
                        {
                            Id = 7,
                            Adults = 2,
                            BookingId = 7,
                            CheckIn = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            PricePerNight = 1799m,
                            RoomId = 3,
                            RoomStatus = 2
                        },
                        new
                        {
                            Id = 8,
                            Adults = 2,
                            BookingId = 8,
                            CheckIn = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 2,
                            PricePerNight = 3499m,
                            RoomId = 5,
                            RoomStatus = 0
                        },
                        new
                        {
                            Id = 9,
                            Adults = 2,
                            BookingId = 9,
                            CheckIn = new DateTime(2026, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 1,
                            PricePerNight = 3499m,
                            RoomId = 5,
                            RoomStatus = 0
                        },
                        new
                        {
                            Id = 10,
                            Adults = 1,
                            BookingId = 10,
                            CheckIn = new DateTime(2027, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2027, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Children = 0,
                            PricePerNight = 999m,
                            RoomId = 1,
                            RoomStatus = 2
                        });
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Booking", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Room", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.RoomCategory", "RoomCategory")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomCategory");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomCategory", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.RoomDetail", "RoomDetail")
                        .WithMany()
                        .HasForeignKey("RoomDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomDetail");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomReservation", b =>
                {
                    b.HasOne("TheGallop_Resort.Models.Models.Booking", "Booking")
                        .WithMany("RoomReservations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGallop_Resort.Models.Models.Room", "Room")
                        .WithMany("RoomReservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Booking", b =>
                {
                    b.Navigation("RoomReservations");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.Room", b =>
                {
                    b.Navigation("RoomReservations");
                });

            modelBuilder.Entity("TheGallop_Resort.Models.Models.RoomCategory", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
